source :rubygems

gem 'rails'

gem 'deltacloud-client', :require => 'deltacloud'
gem 'mustache'
gem 'will_paginate', '>= 3.0.pre1'
gem 'nokogiri'
gem 'simple-navigation'
gem 'rest-client'
gem 'rack-restful_submit'
gem 'uuidtools'
gem 'pg'
gem 'thin'
gem 'json'
gem 'rails_warden'
gem 'ruby-net-ldap', :require => 'net/ldap'
gem 'aeolus-image', :git => "git://github.com/aeolusproject/aeolus-image-rubygem", :require => 'aeolus_image' #'>= 0.4.0',
gem 'oauth'
gem 'ldap_fluff'
gem 'delayed_job', '~> 2.1.4'
gem 'paranoia'
gem 'simple_form', '~> 2.0.3'
gem 'haml-rails'
gem 'sass-rails'
gem 'compass-rails'
gem "alchemy", ">= 1.0.1"

platforms :ruby_18 do
  gem 'fastercsv'
end

group :assets do
  gem 'uglifier'
  gem 'therubyracer'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails', '~> 1.4.0'
  gem 'timecop'
  gem 'capybara'
  gem 'cucumber'
  gem 'cucumber-rails', :require => false
  gem 'database_cleaner'
  gem 'vcr', '< 2.0.0'
  gem 'webmock'
  gem 'launchy'
end
